import fs from 'node:fs/promises';
import path from 'node:path';
import type { PrintJobResult, PrintProviderInfo } from '@tedography/domain';
import { ensureDir, exportPrintJpeg, sequencedFilename } from './printJobService.js';
import type { PrintProvider, ResolvedPrintItem } from './printTypes.js';

const README_CONTENT = `BAY PHOTO PRINT ORDER
=====================

This package was generated by Tedography.

HOW TO ORDER:
1. Go to https://www.bayphoto.com and sign in (or create an account).
2. Choose Online Ordering.
3. Create a new order.
4. Upload all files from the "images/" folder.
5. For each file, select the matching size and finish from order-summary.csv.
6. Set quantity to 1 for every file (quantities > 1 are already reflected
   by the number of files in this package).
7. Review crops and adjust if needed in Bay Photo's UI.
8. Add shipping details and submit.

NOTES:
- Files are named: {seq}__{original}_{size}_{finish}.jpg
- See order-summary.csv or order-summary.html for the full order details.
- Previews are in the "previews/" folder for your reference before uploading.
`;

export class BayPhotoExportProvider implements PrintProvider {
  readonly info: PrintProviderInfo = {
    id: 'bay-photo-export',
    label: 'Bay Photo',
    description: 'Generate a print package for manual upload to bayphoto.com.',
    supportedSizes: ['4x6', '5x7', '8x10', '11x14'],
    supportedFinishes: ['matte', 'lustre', 'glossy'],
    folderPrefix: 'BayPhoto',
  };

  async exportPackage(resolvedItems: ResolvedPrintItem[], outputDir: string): Promise<PrintJobResult> {
    const imagesDir = path.join(outputDir, 'images');
    const previewsDir = path.join(outputDir, 'previews');
    await ensureDir(imagesDir);
    await ensureDir(previewsDir);

    const itemResults: PrintJobResult['items'] = [];
    let totalFiles = 0;
    let warningCount = 0;
    let errorCount = 0;
    let seq = 1;

    const csvRows: string[] = [
      'file,originalFilename,size,finish,quantity,cropMode,warnings',
    ];

    for (const resolved of resolvedItems) {
      const { item, asset } = resolved;
      const exportedFiles: string[] = [];
      let previewFile: string | null = null;

      try {
        for (let q = 1; q <= item.quantity; q++) {
          const suffix = item.quantity > 1 ? `__copy${q}` : '';
          const filename = sequencedFilename(seq, asset.filename, item.size, item.finish, suffix);
          const outputPath = path.join(imagesDir, filename);
          await exportPrintJpeg(resolved, outputPath);
          exportedFiles.push(outputPath);
          totalFiles++;

          const csvWarnings = resolved.resolutionWarnings.join(' | ');
          csvRows.push(
            [
              csvEscape(filename),
              csvEscape(asset.filename),
              item.size,
              item.finish,
              '1',
              item.cropMode,
              csvEscape(csvWarnings),
            ].join(',')
          );
        }

        // preview (just one regardless of quantity)
        const previewFilename = sequencedFilename(seq, asset.filename, item.size, item.finish, '__preview');
        const previewPath = path.join(previewsDir, previewFilename);
        await exportPrintJpeg(resolved, previewPath, true);
        previewFile = previewPath;

        seq++;

        if (resolved.resolutionWarnings.length > 0) warningCount++;
        itemResults.push({
          assetId: item.assetId,
          filename: asset.filename,
          exportedFiles,
          previewFile,
          warnings: resolved.resolutionWarnings,
        });
      } catch (err) {
        errorCount++;
        const message = err instanceof Error ? err.message : String(err);
        itemResults.push({
          assetId: item.assetId,
          filename: asset.filename,
          exportedFiles,
          previewFile,
          warnings: resolved.resolutionWarnings,
          error: message,
        });
        seq++;
      }
    }

    await fs.writeFile(path.join(outputDir, 'order-summary.csv'), csvRows.join('\n') + '\n', 'utf-8');
    await fs.writeFile(path.join(outputDir, 'order-summary.html'), buildHtml(resolvedItems, itemResults), 'utf-8');
    await fs.writeFile(path.join(outputDir, 'README-BayPhoto.txt'), README_CONTENT, 'utf-8');

    return { outputDir, items: itemResults, totalFiles, warningCount, errorCount };
  }
}

function csvEscape(v: string): string {
  return /[",\n]/.test(v) ? `"${v.replace(/"/g, '""')}"` : v;
}

function buildHtml(resolved: ResolvedPrintItem[], results: PrintJobResult['items']): string {
  const rows = resolved.map((r, i) => {
    const result = results[i];
    const warnings = r.resolutionWarnings.map((w) => `<li style="color:#b45309">${w}</li>`).join('');
    const error = result?.error ? `<p style="color:#dc2626">${result.error}</p>` : '';
    const files = result?.exportedFiles.map((f) => `<li>${path.basename(f)}</li>`).join('') ?? '';
    return `
      <tr>
        <td>${r.asset.filename}</td>
        <td>${r.item.size}</td>
        <td>${r.item.finish}</td>
        <td>${r.item.quantity}</td>
        <td>${r.item.cropMode}</td>
        <td><ul style="margin:0;padding-left:14px">${files}</ul></td>
        <td><ul style="margin:0;padding-left:14px">${warnings}</ul>${error}</td>
      </tr>`;
  }).join('');

  return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><title>Bay Photo Print Order</title>
<style>
  body { font-family: Arial, sans-serif; padding: 24px; color: #1f2937; }
  h1 { font-size: 22px; }
  table { border-collapse: collapse; width: 100%; font-size: 13px; }
  th, td { border: 1px solid #d1d5db; padding: 6px 10px; text-align: left; vertical-align: top; }
  th { background: #f3f4f6; font-weight: 600; }
</style>
</head>
<body>
<h1>Bay Photo Print Order</h1>
<p>Generated by Tedography. Upload files from <code>images/</code> to bayphoto.com.</p>
<table>
  <thead><tr>
    <th>Original</th><th>Size</th><th>Finish</th><th>Qty</th><th>Crop</th><th>Files</th><th>Warnings</th>
  </tr></thead>
  <tbody>${rows}</tbody>
</table>
</body></html>`;
}
